services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app

  app1:
    image: php:fpm
    volumes:
      - ./app1/.:/var/www/html/
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - app

  app2:
    image: php:fpm
    volumes:
      - ./app2/.:/var/www/html/
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - app

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app

networks:
  app:
    driver: bridge
